### PR TITLE
Set cell_height from cell_width if not provide.

### PR DESCRIPTION
**Pull request by namerci**
Prevent to crash when we set cell_height to null. Also is helpful if we need square blocks.
.

### CODE REVIEW

**Comment by pySilver** [comment]
@namerci there is console.log left

**Comment by namerci** [comment]
Sorry

**Comment by derekm** [comment]
I tried to implement this today, wanting square cells that scale proportionally as the window is resized. I'd like to resurrect consideration of this feature.

**Comment by troolee** [comment]
I added `'auto'` value for this case. If it's 0 — cell height is taken from CSS

**Pull request closed without merging**
