### PR TITLE
fix ordering of draggable and resizable event callbacks

### LINKED ISSUE #159: Fire onresizestop after complete resizing
When resizing a widget, the dimensions snap to the grid after the handle is released. This is great. :)

screenshot from 2015-06-09 11 56 49

However, it seems that onresizestop() is triggered before that process is finished so if you try to get the widgets dimension, you get them 'wrong'.
Is there a way to get an event that is triggered after the full resizing process?

### PR DESCRIPTION
**Pull request by derekm**
fixes #159 by making grid item callbacks actual event callbacks instead of options callbacks

### CODE REVIEW

**Comment by derekm** [comment]
these fixes impact nest grids, I'm working on a fix for it

**Comment by derekm** [comment]
this would also fix #142

**Comment by troolee** [comment]
Thank you!

I'm on vacation now. Will apply the PR next week.

**Comment by derekm** [comment]
I had put the stop-propagate calls in the wrong place. I'll have more commits today to sort things out.

This also opens a small can of worms related to triggering events between grids (triggering resize events in inner grids when its container is resized in the outer grid, etc.).

**Comment by derekm** [comment]
The above commits put stop-propagation into the correct order. I'm also broadcasting "resizestop" events to nested grids.

Question: Should I broadcast all resize events to nested grids? I, personally, only need resizestop, but I can see where people might need any of the resize events to percolate thru nested grids.

I trigger the resizestop handlers individually so the grid's resizestop events don't fire more than once.

Before broadcasting resizestop, I call the window resize handler `on_resize_handler()`, because I'm using square cells where `cell_height()` is set to `cell_width()`. For others, calling the window resize handler might be a no-op or a wasted effort.

**Comment by derekm** [comment]
Scratch what I said about triggering handlers individually. That idea didn't work out as expected. Grid item's in nested grids need to propagate their events normally, in case grid-level handlers will operate on the grid item via `event.target`.

**Comment by bmatthews99** [comment]
Thanks for this derekm, this fixed my issue. I look forward to seeing it added to the repo.

**Comment by derekm** [comment]
So I've been using this branch with much success in a dashboard product with nested grids.

Yesterday, though, I realized there's an issue with broadcasting "resizestop" events to nested grids. Grid items have a _dirty status that defaults to "true", which is the crux of the problem, and clean_nodes() is used to set all items to "false" before beginning updates.

An outer item that has a nested grid and is being resized may need to broadcast the resizestop event to nested grid items so they can repaint to their new sizes. But since only resizestop is broadcast downwards, the dirty nodes are not "cleaned", and since resizestop fires the "change" event, the change event fires as many times as there are items in the inner grid.

I'm looking for a fix to this that doesn't involve wholly refactoring how nodes are marked dirty, although it is seeming dangerous to default the dirty flag to "true."

**Comment by derekm** [comment]
Broadcasting "resizestart" to inner grids appears to be enough to squelch the proliferation of unwanted "change" events without any undue effects. I'll update this pull request with these improvements soon.

**Comment by derekm** [comment]
The branch has been working great for us for a while now... I think it is safe to consider this for inclusion in gridstack.js proper.

**Comment by joemorcullo8** [comment]
Hi do you have any sample for this? I got lost on what exactly the solution for this. thanks :)

**Pull request merged**
